### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by Yakiyo** [Yakiyo/saki#12]
- [x] Handle music stop command when there is no current queue
- [x] music isn't playing when its running in the vps
- [x] message update should only run when diff in content, nothing else
- [x] avatar update not showing in prod

**Comment by Yakiyo** [comment]
Fixed in #13 and #14

**Comment by ghost** [comment]
> * [x]  avatar update not showing in prod

This not yet

**Comment by Yakiyo** [comment]
oops my bad

**Comment by ghost** [comment]
This is a bit weird as [discord.js docs](https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/discord.js/src/client/actions/UserUpdate.js#L17) state that GuildMemberUpdate is triggered by the UserUpdate gateway event. I guess they changed something when server profile pictures was introduced and forgot to change docs (?)

**Comment by ghost** [comment]
Fixed in #15
